<%@ Page Title="" Language="C#" MasterPageFile="~/_Layout.Master" AutoEventWireup="true" CodeBehind="Elcykler.aspx.cs" Inherits="_3_ugers.Pages.About" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h3 class="widget-title" style="box-sizing: border-box; margin-bottom: 0.5rem; margin-top: 0px; font-weight: 500; line-height: 1.5; color: rgb(17, 17, 17); font-family: montserratbold, Helvetica, Arial, sans-serif; font-size: 1rem; text-transform: uppercase; border-bottom: 2px solid rgb(17, 17, 17); clear: both;">hvem er vi?</h3>
<p>
   Dette er en side for cykelentusiaster – skrevet af cykel-entusiaster. Du vil kunne finde information om El-Cykler, Herre Cykler og Dame cykler og cykelmærker, cykeludstyr, samt gode råd, hvis du skal købe en ny cykel. 
   Du kan også lære, hvordan du vedligeholder din cykel og finde svar på en lang række spørgsmål om landevejscykling og cykling i byer, tips og tricks til at købe den bedste cykel efter dine behov, samt gear og cykelhjul.


</p>
    <p>
        &nbsp;</p>
    <p>
        &nbsp;</p>
    <p>
        <img alt="5 stjerner: Fremragende" src="https://cdn.trustpilot.net/brand-assets/4.1.0/stars/stars-5.svg" />-</p>
    <p>
        Sandra - &quot;Fremragende hjemmeside med mulighed for at undersøge diverse cykler inden man tager en endelig beslutining vedrørende et køb&quot;</p>
    <p>
        Kasper - &quot;Meget brugervenlig hjemmeside. Der findes ikke lignende sider hvor man kan undersøge cyklernes egenskaber. Thumbs up herfra!&quot;</p>
    <p>
        Diana - &quot;Verdens bedste hjemmeside! De har alt hvad man har brug for&quot;</p>
    <p>
        &nbsp;</p>
    <h3 class="widget-title" style="box-sizing: border-box; margin-bottom: 0.5rem; margin-top: 0px; font-weight: 500; line-height: 1.5; color: rgb(17, 17, 17); font-family: montserratbold, Helvetica, Arial, sans-serif; font-size: 1rem; text-transform: uppercase; border-bottom: 2px solid rgb(17, 17, 17); clear: both;">Kontakt os</h3>
    <div class="siteorigin-widget-tinymce textwidget" style="box-sizing: border-box;">
        <p>
            Adresse:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Telefon:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Email:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; CVR:</p>
        <p>
   &nbsp;Lyngbyvej 58&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; +45 54362748&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="mailto:Cykelinfo@info.dk">Cykelinfo@info.dk</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 30504636</p>
        <p>
            2800 Kongens Lyngby&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
        <p>
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="https://www.facebook.com/fribikeshopdk" style="box-sizing: inherit; color: rgb(0, 0, 0); text-decoration: none;" target="_blank">
            <img alt="Facebook" src="https://fricdn.dk//Files/Images/FriBikeShop/Icons2018/Facebook.png?width=40&amp;height=40&amp;format=png&amp;quality=80" style="border-style: none; border-color: inherit; border-width: 0px; box-sizing: inherit; display: inline-block; width: 29px; max-width: 100%; margin: 0px 5px; height: 34px;" /></a><a href="https://www.instagram.com/fribikeshop/" style="box-sizing: inherit; color: rgb(0, 0, 0); text-decoration: none;" target="_blank"><img alt="Instagram" src="https://fricdn.dk//Files/Images/FriBikeShop/Icons2018/Instagram.png?width=40&amp;height=40&amp;format=png&amp;quality=80" style="border-style: none; border-color: inherit; border-width: 0px; box-sizing: inherit; display: inline-block; width: 33px; max-width: 100%; margin: 0px 5px; height: 34px;" /></a><a href="https://www.youtube.com/user/FriBikeshopdk" style="box-sizing: inherit; color: rgb(0, 0, 0); text-decoration: none;" target="_blank"><img alt="Youtube" src="https://fricdn.dk//Files/Images/FriBikeShop/Icons2018/youtube.png?width=40&amp;height=40&amp;format=png&amp;quality=80" style="border-style: none; border-color: inherit; border-width: 0px; box-sizing: inherit; display: inline-block; width: 37px; max-width: 100%; margin: 0px 5px; height: 38px;" /></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="tel:+4544221016" style="box-sizing: inherit; color: rgb(228, 0, 63); text-decoration: none; outline: 0px;"><picture style="box-sizing: inherit;">
            <img alt="Phone" src="https://fricdn.dk//Files/Images/FriBikeShop/Icons2018/phone.png?width=60&amp;height=60&amp;format=png&amp;quality=80" style="border-style: none; border-color: inherit; border-width: 0px; box-sizing: inherit; display: inline-block; width: 47px; max-width: 100%; margin: 0px 5px; height: 43px;" /></picture></a><a href="https://www.fribikeshop.dk/kontakt" style="box-sizing: inherit; color: rgb(0, 0, 0); text-decoration: none;"><picture style="box-sizing: inherit;"><img alt="Mail" src="https://fricdn.dk//Files/Images/FriBikeShop/Icons2018/Mail.png?width=60&amp;height=60&amp;format=png&amp;quality=80" style="border-style: none; border-color: inherit; border-width: 0px; box-sizing: inherit; display: inline-block; width: 42px; max-width: 100%; margin: 0px 5px; height: 44px;" /></picture></a><a class="footer__spot-chat js-open-chat" style="box-sizing: inherit; color: rgb(0, 0, 0); text-decoration: none; cursor: pointer;"><img alt="Chat" src="https://fricdn.dk//Files/Images/FriBikeShop/Icons2018/chat.png?width=60&amp;height=60&amp;format=png&amp;quality=80" style="border-style: none; border-color: inherit; border-width: 0px; box-sizing: inherit; display: inline-block; width: 43px; max-width: 100%; margin: 0px 5px; height: 45px;" /></a></p>
        <p>
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
            Følg med&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Kundeservice man-fre kl- 9-16</p>
        <p style="margin-left: 840px">
            &nbsp;</p>
    </div>
</asp:Content>
